FROM python:3.7-alpine

COPY ./app/common/ /app/common/
COPY ./app/recipient_list.py /app/
COPY ./app/requirements.txt /app/

RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

WORKDIR /app/
CMD ["python", "./recipient_list.py"]
